#  Template python-build

#  This template allows you to validate your python code.
#  The workflow allows running tests and code linting on the default branch.

image: python:3.7

pipelines:
  default:
    - step:
        name: Lint code
        caches:
          - pip
        script:
          - pip install flake8
          - flake8 . --extend-exclude=dist,build --show-source --statistics --ignore=E501
